[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE = "/"

[[redirects]]
  from = "/api/*"
  to = "https://pricechecknow-5vrb.onrender.com/api/:splat"
  status = 200
  force = true

# SPA fallback: send all other routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


